"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 14:32:58.722884

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("SET LOCAL max_parallel_maintenance_workers = 0")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_tokens')),
    sa.UniqueConstraint('name', name=op.f('uq_api_tokens_name'))
    )
    op.create_table('bug_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bug_key', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('severity', sa.String(length=4), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('reproduction', sa.Text(), nullable=True),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('regression_test', sa.Text(), nullable=True),
    sa.Column('fix_commit', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bug_records')),
    sa.UniqueConstraint('bug_key', name=op.f('uq_bug_records_bug_key'))
    )
    op.create_table('code_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_key', sa.String(length=300), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_chunks'))
    )
    op.create_index('ix_code_chunks_embedding_hnsw', 'code_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_code_chunks_repo_path', 'code_chunks', ['repository_key', 'path'], unique=False)
    op.create_index(op.f('ix_code_chunks_repository_key'), 'code_chunks', ['repository_key'], unique=False)
    op.create_table('code_symbols',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_key', sa.String(length=300), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('parent', sa.String(length=300), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_code_symbols'))
    )
    op.create_index(op.f('ix_code_symbols_name'), 'code_symbols', ['name'], unique=False)
    op.create_index('ix_code_symbols_repo_path', 'code_symbols', ['repository_key', 'path'], unique=False)
    op.create_index(op.f('ix_code_symbols_repository_key'), 'code_symbols', ['repository_key'], unique=False)
    op.create_table('command_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('tool_call_id', sa.UUID(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('cwd', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('network', sa.Boolean(), nullable=False),
    sa.Column('stdout_excerpt', sa.Text(), nullable=True),
    sa.Column('stderr_excerpt', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_runs'))
    )
    op.create_index(op.f('ix_command_runs_job_id'), 'command_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_command_runs_step_id'), 'command_runs', ['step_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('rollback_artifact_id', sa.UUID(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    op.create_index(op.f('ix_deployments_job_id'), 'deployments', ['job_id'], unique=False)
    op.create_table('events',
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('correlation_id', sa.String(length=200), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sequence', name=op.f('pk_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_events_event_id'))
    )
    op.create_index(op.f('ix_events_correlation_id'), 'events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_job_id'), 'events', ['job_id'], unique=False)
    op.create_index('ix_events_job_sequence', 'events', ['job_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_events_step_id'), 'events', ['step_id'], unique=False)
    op.create_table('git_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ref', sa.String(length=300), nullable=True),
    sa.Column('sha_before', sa.String(length=64), nullable=True),
    sa.Column('sha_after', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_git_operations'))
    )
    op.create_index(op.f('ix_git_operations_job_id'), 'git_operations', ['job_id'], unique=False)
    op.create_index(op.f('ix_git_operations_workspace_id'), 'git_operations', ['workspace_id'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_entries'))
    )
    op.create_table('model_invocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_chars', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=32), nullable=True),
    sa.Column('response_valid', sa.Boolean(), nullable=True),
    sa.Column('repair_attempt', sa.Integer(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_invocations'))
    )
    op.create_index(op.f('ix_model_invocations_alias'), 'model_invocations', ['alias'], unique=False)
    op.create_index(op.f('ix_model_invocations_job_id'), 'model_invocations', ['job_id'], unique=False)
    op.create_index(op.f('ix_model_invocations_step_id'), 'model_invocations', ['step_id'], unique=False)
    op.create_table('model_profiles',
    sa.Column('alias', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('host_worker_id', sa.String(length=100), nullable=True),
    sa.Column('context_tokens', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('resource_group', sa.String(length=100), nullable=False),
    sa.Column('exclusive', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('memory_gb', sa.Float(), nullable=False),
    sa.Column('fallback_for', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('alias', name=op.f('pk_model_profiles'))
    )
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('default_branch', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('gitlab_project_id', sa.String(length=200), nullable=True),
    sa.Column('protected_branches', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories')),
    sa.UniqueConstraint('name', name=op.f('uq_repositories_name'))
    )
    op.create_table('resource_leases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('resource_group', sa.String(length=100), nullable=False),
    sa.Column('owner_job_id', sa.UUID(), nullable=True),
    sa.Column('owner_step_id', sa.UUID(), nullable=True),
    sa.Column('owner_kind', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('preemptible', sa.Boolean(), nullable=False),
    sa.Column('exclusive', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_leases'))
    )
    op.create_index(op.f('ix_resource_leases_owner_job_id'), 'resource_leases', ['owner_job_id'], unique=False)
    op.create_index(op.f('ix_resource_leases_owner_step_id'), 'resource_leases', ['owner_step_id'], unique=False)
    op.create_index(op.f('ix_resource_leases_resource'), 'resource_leases', ['resource'], unique=False)
    op.create_index('ix_resource_leases_state_expires', 'resource_leases', ['state', 'expires_at'], unique=False)
    op.create_index('uq_resource_leases_exclusive_active', 'resource_leases', ['resource'], unique=True, postgresql_where=sa.text("exclusive = true AND state IN ('active','preempting')"))
    op.create_table('resource_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('owner_job_id', sa.UUID(), nullable=True),
    sa.Column('owner_step_id', sa.UUID(), nullable=True),
    sa.Column('owner_kind', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_requests'))
    )
    op.create_index(op.f('ix_resource_requests_resource'), 'resource_requests', ['resource'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('output_excerpt', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_runs'))
    )
    op.create_index(op.f('ix_test_runs_job_id'), 'test_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_test_runs_step_id'), 'test_runs', ['step_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=64), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls'))
    )
    op.create_index(op.f('ix_tool_calls_attempt_id'), 'tool_calls', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_job_id'), 'tool_calls', ['job_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_step_id'), 'tool_calls', ['step_id'], unique=False)
    op.create_table('wake_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wake_events'))
    )
    op.create_index(op.f('ix_wake_events_worker_id'), 'wake_events', ['worker_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('worker_version', sa.String(length=64), nullable=True),
    sa.Column('protocol_version', sa.Integer(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_job_id', sa.String(length=64), nullable=True),
    sa.Column('active_step_id', sa.String(length=64), nullable=True),
    sa.Column('wol', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers'))
    )
    op.create_index(op.f('ix_workers_state'), 'workers', ['state'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('base_branch', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('current_plan_version', sa.Integer(), nullable=True),
    sa.Column('replan_count', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_owner', sa.String(length=200), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority BETWEEN 0 AND 100', name=op.f('ck_jobs_priority_range')),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_jobs_repository_id_repositories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_repository_id'), 'jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_status_priority', 'jobs', ['status', 'priority'], unique=False)
    op.create_table('worker_capabilities',
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_capabilities_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id', 'capability', name=op.f('pk_worker_capabilities'))
    )
    op.create_table('worker_health',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('ram_total_mb', sa.Integer(), nullable=False),
    sa.Column('ram_used_mb', sa.Integer(), nullable=False),
    sa.Column('disk_free_mb', sa.Integer(), nullable=False),
    sa.Column('gpus', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('loaded_models', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('active_job', sa.String(length=64), nullable=True),
    sa.Column('active_step', sa.String(length=64), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('service_versions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_health_worker_id_workers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_health'))
    )
    op.create_index(op.f('ix_worker_health_worker_id'), 'worker_health', ['worker_id'], unique=False)
    op.create_table('job_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_inputs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_inputs'))
    )
    op.create_index(op.f('ix_job_inputs_job_id'), 'job_inputs', ['job_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_plans_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_job_id'), 'plans', ['job_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('branch', sa.String(length=300), nullable=False),
    sa.Column('base_branch', sa.String(length=200), nullable=False),
    sa.Column('base_sha', sa.String(length=64), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_workspaces_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_workspaces_repository_id_repositories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_job_id'), 'workspaces', ['job_id'], unique=False)
    op.create_index(op.f('ix_workspaces_repository_id'), 'workspaces', ['repository_id'], unique=False)
    op.create_table('plan_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('model_alias', sa.String(length=100), nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_plan_versions_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_versions_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_versions')),
    sa.UniqueConstraint('plan_id', 'version', name='plan_version')
    )
    op.create_index(op.f('ix_plan_versions_job_id'), 'plan_versions', ['job_id'], unique=False)
    op.create_index(op.f('ix_plan_versions_plan_id'), 'plan_versions', ['plan_id'], unique=False)
    op.create_table('repo_index_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('git_sha', sa.String(length=64), nullable=False),
    sa.Column('base_index_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('inventory', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repo_index_runs_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_repo_index_runs_workspace_id_workspaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repo_index_runs'))
    )
    op.create_index(op.f('ix_repo_index_runs_repository_id'), 'repo_index_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_repo_index_runs_workspace_id'), 'repo_index_runs', ['workspace_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('plan_version_id', sa.UUID(), nullable=True),
    sa.Column('step_key', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('acceptance', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('repo_hints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('preferred_worker_capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('allowed_new_paths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('forbidden_paths', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('network', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correction_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('turn_budget', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('assigned_worker_id', sa.String(length=100), nullable=True),
    sa.Column('current_scope_version', sa.Integer(), nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=200), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_steps_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_versions.id'], name=op.f('fk_steps_plan_version_id_plan_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_steps'))
    )
    op.create_index(op.f('ix_steps_job_id'), 'steps', ['job_id'], unique=False)
    op.create_index('ix_steps_job_key_active', 'steps', ['job_id', 'step_key'], unique=True, postgresql_where=sa.text('superseded = false'))
    op.create_index(op.f('ix_steps_plan_version_id'), 'steps', ['plan_version_id'], unique=False)
    op.create_index(op.f('ix_steps_status'), 'steps', ['status'], unique=False)
    op.create_index('ix_steps_status_priority', 'steps', ['status', 'priority'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_artifacts_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], name=op.f('fk_artifacts_step_id_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifacts_step_id'), 'artifacts', ['step_id'], unique=False)
    op.create_table('research_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('queries', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('synthesis', sa.Text(), nullable=True),
    sa.Column('contradictions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_alias', sa.String(length=100), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_research_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], name=op.f('fk_research_runs_step_id_steps'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs'))
    )
    op.create_index(op.f('ix_research_runs_job_id'), 'research_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_research_runs_step_id'), 'research_runs', ['step_id'], unique=False)
    op.create_table('review_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('model_alias', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('raw_verdict', sa.String(length=32), nullable=True),
    sa.Column('invariant_override', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_review_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], name=op.f('fk_review_runs_step_id_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_runs'))
    )
    op.create_index(op.f('ix_review_runs_job_id'), 'review_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_review_runs_step_id'), 'review_runs', ['step_id'], unique=False)
    op.create_table('scope_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('contract', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_scope_contracts_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], name=op.f('fk_scope_contracts_step_id_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_contracts')),
    sa.UniqueConstraint('step_id', 'version', name='scope_step_version')
    )
    op.create_index(op.f('ix_scope_contracts_job_id'), 'scope_contracts', ['job_id'], unique=False)
    op.create_index(op.f('ix_scope_contracts_step_id'), 'scope_contracts', ['step_id'], unique=False)
    op.create_table('step_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('model_alias', sa.String(length=100), nullable=True),
    sa.Column('turns_used', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('fingerprints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('correction_input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_step_attempts_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], name=op.f('fk_step_attempts_step_id_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_step_attempts')),
    sa.UniqueConstraint('step_id', 'attempt_no', name='step_attempt_no')
    )
    op.create_index(op.f('ix_step_attempts_job_id'), 'step_attempts', ['job_id'], unique=False)
    op.create_index(op.f('ix_step_attempts_step_id'), 'step_attempts', ['step_id'], unique=False)
    op.create_table('step_dependencies',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_step_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('step_id <> depends_on_step_id', name=op.f('ck_step_dependencies_no_self_dependency')),
    sa.ForeignKeyConstraint(['depends_on_step_id'], ['steps.id'], name=op.f('fk_step_dependencies_depends_on_step_id_steps'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], name=op.f('fk_step_dependencies_step_id_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id', 'depends_on_step_id', name=op.f('pk_step_dependencies'))
    )
    op.create_index(op.f('ix_step_dependencies_depends_on_step_id'), 'step_dependencies', ['depends_on_step_id'], unique=False)
    op.create_table('verification_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('changed_files', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_verification_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], name=op.f('fk_verification_runs_step_id_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_runs'))
    )
    op.create_index(op.f('ix_verification_runs_job_id'), 'verification_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_verification_runs_step_id'), 'verification_runs', ['step_id'], unique=False)
    op.create_table('research_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('used_for_decision', sa.Boolean(), nullable=False),
    sa.Column('decision_ref', sa.Text(), nullable=True),
    sa.Column('contradiction_group', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_research_claims_research_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_claims'))
    )
    op.create_index(op.f('ix_research_claims_research_run_id'), 'research_claims', ['research_run_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=300), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('authority_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_research_sources_research_run_id_research_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sources'))
    )
    op.create_index(op.f('ix_research_sources_research_run_id'), 'research_sources', ['research_run_id'], unique=False)
    op.create_table('review_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_run_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['review_run_id'], ['review_runs.id'], name=op.f('fk_review_findings_review_run_id_review_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_findings'))
    )
    op.create_index(op.f('ix_review_findings_review_run_id'), 'review_findings', ['review_run_id'], unique=False)
    op.create_table('verification_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_run_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], name=op.f('fk_verification_checks_verification_run_id_verification_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_checks'))
    )
    op.create_index(op.f('ix_verification_checks_verification_run_id'), 'verification_checks', ['verification_run_id'], unique=False)
    op.create_table('research_claim_sources',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['research_claims.id'], name=op.f('fk_research_claim_sources_claim_id_research_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['research_sources.id'], name=op.f('fk_research_claim_sources_source_id_research_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'source_id', name=op.f('pk_research_claim_sources'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_claim_sources')
    op.drop_index(op.f('ix_verification_checks_verification_run_id'), table_name='verification_checks')
    op.drop_table('verification_checks')
    op.drop_index(op.f('ix_review_findings_review_run_id'), table_name='review_findings')
    op.drop_table('review_findings')
    op.drop_index(op.f('ix_research_sources_research_run_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_claims_research_run_id'), table_name='research_claims')
    op.drop_table('research_claims')
    op.drop_index(op.f('ix_verification_runs_step_id'), table_name='verification_runs')
    op.drop_index(op.f('ix_verification_runs_job_id'), table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_step_dependencies_depends_on_step_id'), table_name='step_dependencies')
    op.drop_table('step_dependencies')
    op.drop_index(op.f('ix_step_attempts_step_id'), table_name='step_attempts')
    op.drop_index(op.f('ix_step_attempts_job_id'), table_name='step_attempts')
    op.drop_table('step_attempts')
    op.drop_index(op.f('ix_scope_contracts_step_id'), table_name='scope_contracts')
    op.drop_index(op.f('ix_scope_contracts_job_id'), table_name='scope_contracts')
    op.drop_table('scope_contracts')
    op.drop_index(op.f('ix_review_runs_step_id'), table_name='review_runs')
    op.drop_index(op.f('ix_review_runs_job_id'), table_name='review_runs')
    op.drop_table('review_runs')
    op.drop_index(op.f('ix_research_runs_step_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_job_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_artifacts_step_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_steps_status_priority', table_name='steps')
    op.drop_index(op.f('ix_steps_status'), table_name='steps')
    op.drop_index(op.f('ix_steps_plan_version_id'), table_name='steps')
    op.drop_index('ix_steps_job_key_active', table_name='steps', postgresql_where=sa.text('superseded = false'))
    op.drop_index(op.f('ix_steps_job_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_repo_index_runs_workspace_id'), table_name='repo_index_runs')
    op.drop_index(op.f('ix_repo_index_runs_repository_id'), table_name='repo_index_runs')
    op.drop_table('repo_index_runs')
    op.drop_index(op.f('ix_plan_versions_plan_id'), table_name='plan_versions')
    op.drop_index(op.f('ix_plan_versions_job_id'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_workspaces_repository_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_job_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_plans_job_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_job_inputs_job_id'), table_name='job_inputs')
    op.drop_table('job_inputs')
    op.drop_index(op.f('ix_worker_health_worker_id'), table_name='worker_health')
    op.drop_table('worker_health')
    op.drop_table('worker_capabilities')
    op.drop_index('ix_jobs_status_priority', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_repository_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_workers_state'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_wake_events_worker_id'), table_name='wake_events')
    op.drop_table('wake_events')
    op.drop_index(op.f('ix_tool_calls_step_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_job_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_attempt_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_test_runs_step_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_job_id'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_resource_requests_resource'), table_name='resource_requests')
    op.drop_table('resource_requests')
    op.drop_index('uq_resource_leases_exclusive_active', table_name='resource_leases', postgresql_where=sa.text("exclusive = true AND state IN ('active','preempting')"))
    op.drop_index('ix_resource_leases_state_expires', table_name='resource_leases')
    op.drop_index(op.f('ix_resource_leases_resource'), table_name='resource_leases')
    op.drop_index(op.f('ix_resource_leases_owner_step_id'), table_name='resource_leases')
    op.drop_index(op.f('ix_resource_leases_owner_job_id'), table_name='resource_leases')
    op.drop_table('resource_leases')
    op.drop_table('repositories')
    op.drop_table('model_profiles')
    op.drop_index(op.f('ix_model_invocations_step_id'), table_name='model_invocations')
    op.drop_index(op.f('ix_model_invocations_job_id'), table_name='model_invocations')
    op.drop_index(op.f('ix_model_invocations_alias'), table_name='model_invocations')
    op.drop_table('model_invocations')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_git_operations_workspace_id'), table_name='git_operations')
    op.drop_index(op.f('ix_git_operations_job_id'), table_name='git_operations')
    op.drop_table('git_operations')
    op.drop_index(op.f('ix_events_step_id'), table_name='events')
    op.drop_index('ix_events_job_sequence', table_name='events')
    op.drop_index(op.f('ix_events_job_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_correlation_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_deployments_job_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_command_runs_step_id'), table_name='command_runs')
    op.drop_index(op.f('ix_command_runs_job_id'), table_name='command_runs')
    op.drop_table('command_runs')
    op.drop_index(op.f('ix_code_symbols_repository_key'), table_name='code_symbols')
    op.drop_index('ix_code_symbols_repo_path', table_name='code_symbols')
    op.drop_index(op.f('ix_code_symbols_name'), table_name='code_symbols')
    op.drop_table('code_symbols')
    op.drop_index(op.f('ix_code_chunks_repository_key'), table_name='code_chunks')
    op.drop_index('ix_code_chunks_repo_path', table_name='code_chunks')
    op.drop_index('ix_code_chunks_embedding_hnsw', table_name='code_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('code_chunks')
    op.drop_table('bug_records')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
