"""Generate the LiteLLM proxy ``config.yaml`` from ``models.yaml`` (P08 8.1/8.2).

    python -m hermclaw.models.litellm_config OUT [--config-dir DIR] [--keep-alive 10m] [--ollama-url HOST=URL ...]

* ``model_list[].model_name`` = Hermclaw alias; chat profiles route to ``ollama_chat/<tag>`` (Ollama ``/api/chat``),
  embedding profiles to ``ollama/<tag>`` (``/api/embed``).
* ``num_ctx``, ``keep_alive`` and ``think`` are set per deployment as defaults; the gateway additionally sends them per
  request (verified pass-through, see docs/architecture/models.md), so both paths agree.
* ``num_retries: 0`` / ``disable_cooldowns``: retries and fallbacks are decided by the Hermclaw gateway (documented,
  evented) – LiteLLM must not retry or switch models silently.
* ``background_health_checks: false``: LiteLLM health checks send real completions and would load models on the
  model host behind the resource manager's back.
* The master key is never written into the file: ``os.environ/LITELLM_MASTER_KEY`` (systemd credential → env).
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import yaml

from hermclaw.core.config import HostsConfig, ModelProfileConfig, ModelsConfig
from hermclaw.core.errors import ConfigError
from hermclaw.models.profiles import ProfileRegistry, assert_architecture, ollama_base_url, validate_http_url

DEFAULT_MASTER_KEY_ENV = "LITELLM_MASTER_KEY"
HEADER = "# Generated by `python -m hermclaw.models.litellm_config` from models.yaml – do not edit by hand.\n"


def _deployment(profile: ModelProfileConfig, api_base: str, *, keep_alive: str | None) -> dict[str, Any]:
    params: dict[str, Any] = {
        "model": f"{'ollama_chat' if profile.kind == 'chat' else 'ollama'}/{profile.model}",
        "api_base": api_base,
        "num_ctx": profile.context_tokens,
        "timeout": profile.timeout_seconds,
    }
    if keep_alive:
        params["keep_alive"] = keep_alive
    info: dict[str, Any] = {"mode": profile.kind, "max_input_tokens": profile.context_tokens}
    if profile.kind == "chat":
        params["think"] = profile.think
        info["max_output_tokens"] = profile.max_output_tokens
    elif profile.embedding_dimensions:
        info["output_vector_size"] = profile.embedding_dimensions
    return {"model_name": profile.alias, "litellm_params": params, "model_info": info}


def build_litellm_config(
    models: ModelsConfig,
    *,
    ollama_urls_by_host: Mapping[str, str],
    keep_alive: str | None = "10m",
    master_key_env: str = DEFAULT_MASTER_KEY_ENV,
    check_architecture: bool = True,
) -> dict[str, Any]:
    """Build the LiteLLM proxy configuration (as a dict) for all enabled profiles."""
    if check_architecture:
        assert_architecture(models)
    if not master_key_env.isidentifier():
        raise ConfigError("master_key_env must be an environment variable name", code="CONFIG_INVALID")
    model_list: list[dict[str, Any]] = []
    for profile in ProfileRegistry(models).enabled():
        url = ollama_urls_by_host.get(profile.host)
        if url is None:
            raise ConfigError(f"no Ollama URL for host '{profile.host}' (alias '{profile.alias}')", code="CONFIG_INVALID")
        model_list.append(_deployment(profile, validate_http_url(url, what=f"ollama url of {profile.host}"), keep_alive=keep_alive))
    timeout = models.litellm.request_timeout_seconds
    return {
        "model_list": model_list,
        "litellm_settings": {"drop_params": False, "num_retries": 0, "request_timeout": timeout},
        "router_settings": {"num_retries": 0, "timeout": timeout, "disable_cooldowns": True},
        "general_settings": {
            "master_key": f"os.environ/{master_key_env}",
            "background_health_checks": False,
            "health_check_details": False,
        },
    }


def render_litellm_config(config: Mapping[str, Any]) -> str:
    return HEADER + yaml.safe_dump(dict(config), sort_keys=False, allow_unicode=True)


def write_litellm_config(path: Path, config: Mapping[str, Any]) -> Path:
    """Atomically write the rendered config (mode 0644 – it contains no secrets)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix=".litellm-", suffix=".yaml", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(render_litellm_config(config))
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    return path


def _parse_overrides(values: Sequence[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for item in values:
        host, sep, url = item.partition("=")
        if not sep or not host or not url:
            raise ConfigError(f"--ollama-url expects HOST=URL, got '{item}'", code="CONFIG_INVALID")
        out[host] = validate_http_url(url, what=f"ollama url of {host}")
    return out


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m hermclaw.models.litellm_config", description=__doc__.split("\n\n")[0])
    parser.add_argument("out", type=Path, help="output path of the LiteLLM config.yaml ('-' for stdout)")
    parser.add_argument("--config-dir", type=Path, default=None, help="Hermclaw config directory (default: HERMCLAW_CONFIG_DIR)")
    parser.add_argument("--keep-alive", default="10m", help="Ollama keep_alive per deployment (default 10m)")
    parser.add_argument("--master-key-env", default=DEFAULT_MASTER_KEY_ENV)
    parser.add_argument("--ollama-url", action="append", default=[], metavar="HOST=URL", help="override the Ollama URL of a model host")
    args = parser.parse_args(list(argv) if argv is not None else None)
    from hermclaw.core.config import load_config

    try:
        cfg = load_config(args.config_dir)
        urls = _ollama_urls(cfg.hosts, cfg.models, _parse_overrides(args.ollama_url))
        config = build_litellm_config(
            cfg.models, ollama_urls_by_host=urls, keep_alive=args.keep_alive or None, master_key_env=args.master_key_env
        )
    except ConfigError as exc:
        print(f"error: {exc.message}", file=sys.stderr)
        return 2
    if str(args.out) == "-":
        sys.stdout.write(render_litellm_config(config))
    else:
        write_litellm_config(args.out, config)
        print(f"wrote {args.out} ({len(config['model_list'])} deployments)")
    return 0


def _ollama_urls(hosts: HostsConfig, models: ModelsConfig, overrides: Mapping[str, str]) -> dict[str, str]:
    return {h: overrides[h] if h in overrides else ollama_base_url(hosts, h) for h in ProfileRegistry(models).hosts()}


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
